### PR TITLE
August blog entry

### PR DESCRIPTION
**Pull request by Lorenz-U**
Hi @bailliem,
I created a branch for the August entry (sorry for the name "september"; I started working on the September entry and did not create a separate branch for the August entry...). I saw your name in the list for the August entry. You can add a summary by updating the file /_posts/2021-09-05-wonderful-wednesdays-august-2021/wonderful-wednesdays-august-2021.Rmd. Please let me know if you do not have time for that. Thanks!

### CODE REVIEW

**Comment by bailliem** [comment]
Thanks @Lorenz-U I have the text, will try to complete tomorrow

**Comment by Lorenz-U** [comment]
@bailliem, great, thank you! You can also just send me the text, if you prefer...

**Comment by bailliem** [comment]
@Lorenz-U  - I've added the August entry on a different branch #3

**Comment by Lorenz-U** [comment]
Thanks @bailliem!

**Comment by Lorenz-U** [comment]
Delete this branch. The September entry is on a separate branch now (#4).

**Pull request closed without merging**
